### ISSUE TITLE
Something not working after 200k++ games

### ISSUE THREAD

**Issue by Josema** [kenany/glicko2-lite#208]
I'm testing this library and something really weird is happening in the calculations after two players play more than 250000.

Everything fine with 200000 games:
```
┌─────────┬────────┬────────┬────────┬──────────────────────────────────────────────────────────────────────────────────┐
│ (index) │ games  │  wins  │ loses  │                                       elo                                        │
├─────────┼────────┼────────┼────────┼──────────────────────────────────────────────────────────────────────────────────┤
│    0    │ 200000 │ 99392  │ 100608 │ '{"rating":1461.5922282897523,"rd":89.48289206147666,"vol":0.12741192063721435}' │
│    1    │ 200000 │ 100608 │ 99392  │ '{"rating":1538.4077665389825,"rd":89.48289317477665,"vol":0.12741192397962253}' │
└─────────┴────────┴────────┴────────┴──────────────────────────────────────────────────────────────────────────────────┘
```

Something is broken at 250000:
```
┌─────────┬────────┬────────┬────────┬───────────────────────────────────────────────────────────────────────────────────┐
│ (index) │ games  │  wins  │ loses  │                                        elo                                        │
├─────────┼────────┼────────┼────────┼───────────────────────────────────────────────────────────────────────────────────┤
│    0    │ 250000 │ 124906 │ 125094 │ '{"rating":-96757575492711300000,"rd":9254368232325.232,"vol":352411320.0301152}' │
│    1    │ 250000 │ 125094 │ 124906 │  '{"rating":-8100.427380765521,"rd":797630.1725974662,"vol":30.356137410080162}'  │
└─────────┴────────┴────────┴────────┴───────────────────────────────────────────────────────────────────────────────────┘
```

Here is the code:
```js
const glicko2 = require('glicko2-lite')

const players = createPlayers(2)

for (let repeat = 0; repeat < 250000; ++repeat) {
    const [playerid1, playerid2] = pickTwoRandomItems(players)
    const winner = players[playerid1]
    const looser = players[playerid2]
    const result = calcRating({ winner: winner.elo, looser: looser.elo })
    winner.wins += 1
    looser.loses += 1
    winner.elo = result.winner
    looser.elo = result.looser
}

console.table(
    players.reverse().map((p) => ({
        // rating: Math.round(p.elo.rating),
        // id: p.chances,
        games: p.wins + p.loses,
        wins: p.wins,
        loses: p.loses,
        elo: JSON.stringify(p.elo),
    }))
)

/// ----------------------------------

function createPlayerRating({ rating = 1500, rd = 200, vol = 0.06 }) {
    return {
        rating,
        rd,
        vol,
    }
}

function calcRating({ winner, looser, draw = false, tau = 0.5 }) {
    return {
        winner: glicko2(
            winner.rating,
            winner.rd,
            winner.vol,
            [[looser.rating, looser.rd, draw ? 0.5 : 1]],
            { tau }
        ),
        looser: glicko2(
            looser.rating,
            looser.rd,
            looser.vol,
            [[winner.rating, winner.rd, draw ? 0.5 : 0]],
            { tau }
        ),
    }
}

function randomInt(min, max) {
    const i = (Math.random() * 32768) >>> 0
    return (i % (min - (max + 1))) + min
}

function createPlayers(n) {
    return Array.from(Array(n)).map((p, index) => {
        return {
            chances: index,
            wins: 0,
            loses: 0,
            elo: createPlayerRating({}),
        }
    })
}

function pickTwoRandomItems(array) {
    let first = randomInt(0, array.length - 1)
    let second
    do {
        second = randomInt(0, array.length - 1)
    } while (first === second)
    return [first, second]
}
```

**Comment by kenany** [comment]
The rating deviations and volatilities are never stabilizing and eventually grow to a point where they begin to drastically increase with each match. I suspect this is a consequence of neither player here being better than the other, it's all just random chance who wins, so player strength is not being measured.

![image](https://github.com/kenany/glicko2-lite/assets/733364/bcf56af9-d099-4fd8-b816-5940335a5b35)
![image](https://github.com/kenany/glicko2-lite/assets/733364/dd1caeeb-61f3-4c69-8771-215e088679f3)

At some point around `repeat = 227098`, one of the player's ratings goes negative. The Glicko-2 paper does not address negative values so I probably won't do that in this package, instead I will leave it to the consumer to decide what to do with extremely-low-rated players.

Since this is a [random walk](https://en.wikipedia.org/wiki/Random_walk) one player will rack up more wins than the other:

![image](https://github.com/kenany/glicko2-lite/assets/733364/f06f89d4-18a2-454a-ab8e-1fdf9991b95d)

but despite this record they'll still lose 50% of future games by chance so their rating, and the other player's, jump around all over the place until eventually they reach extreme values and I guess overflow into the negative values you saw.

So, I don't think you found an issue with this package, but perhaps rather with the Glicko-2 algorithm when taken to the extreme you've demonstrated.

**Comment by Josema** [comment]
I did the same tests for https://github.com/mmai/glicko2js and https://github.com/animafps/glicko2.ts, and both of them breaks at some point. So I guess it is a problem of the glicko2 algorithm, as you pointed out.

`I suspect this is a consequence of neither player here being better than the other, it's all just random chance who wins, so player strength is not being measured.`

But that is not how it should work. If our level is fully equal, the algorithm should represent it even if we play 1vs1 for eternity. Does not make any sense that our rating gets negative at certain number of games.

This is clearly a glitch in the algorithm. I know that this problem would only happen in extreme cases, but it feels mathematically incorrect.

By the way, I did some tests with multiple players and different win-ratios and all of them started to break after 200k++ games.

I have not read the glicko2 paper. But is there a possibility that the implementation requires to recalculate the rating of all the players to avoid this problem? 

Maybe that is why https://github.com/mmai/glicko2js store an instance of every player and then runs `ranking.updateRatings(matches)`.

**Comment by Josema** [comment]
Where did you get the chart about rating deviation? I'd like to read more about this. I tried the same test with the [elo rating system](https://github.com/dmamills/elo-rank) and it works ok in extreme scenarios. So definitely something is wrong with glicko2.

**Comment by kenany** [comment]
Made the graphs myself, basically just saved the rating deviation of player 0 over time to a CSV file and then plotted it with R.
